### PR TITLE
Add French translation file

### PR DESCRIPTION
**Pull request by Darknior**
I translate your English file

### CODE REVIEW

**Comment by gazpan** [comment]
Hi, thanks for this, I'm sure there are many words and messages that are not controlled by language though, I will have a look to see the most obvious but if you know of any text that needs it most then let me know and I will do that first. Merci!

**Comment by gazpan** [comment]
... it's ok to merge #13 ... do I need to do anything with #11 and #12 ?

... my first GitHub merge!

**Comment by Darknior** [comment]
Cool for your first merge :)

> I will have a look to see the most obvious but if you know of any text that needs it most then let me know and I will do that first. Merci!

Yes i have see some, i will make a list ;)
I think it is hard coded in your program.

**Comment by Darknior** [comment]
French is working fine, other TEXT to translate : 

On SYSTEM list : 
- ?? GAMES AVAILABLE : Jeux disponibles

Bottom menu : OPTIONS
- SCAN : Scanner
- MATCH MEDIA -> What will it do ?
- NEW FOLDER : Ajouter un dossier (Not working now)
- UPLOAD ROMS : Envoyer des roms (Not working now)

Bottom menu : VIEW
- BASIC : Basique
- DETAILED : Détaillé
- VIDEO : Vidéo

Game EDIT : 
- CLEAR : Effacer

MAIN MENU : Menu principal
- UI SETTINGS : Configuration de l'interface
-- THEME SET : Choix du thème
-- VIEW TRANSITIONS : Effets de transition
-- GAMELIST VIEW STYLE : Style des listes de jeux
-- LANGUAGE : Choix de la langue
-- DATE FORMAT : Format de la date
- OTHER SETTINGS : Autres réglages
-- SCAN FOR NEW GAMES AT START : Scanner les nouveaux jeux au démarage
-- SHOW EMPTY SYSTEMS : Afficher les systèmes vides
-- SHOW EMPTY NEW DIRECTORIES : Afficher les nouveaux dossiers vides
- HELPBAR SETTINGS : Réglages de la barre d'aide
-- SHOW FILTERED/TOTAL GAME COUNT : Compteur des jeux filtrés/total
-- SHOW ADD/REMOVE LIST COLUMNS : Ajouter/Supprimer des colonnes
-- SHOW THEME SELECT : Choix du thème
-- SHOW VIEW SELECT : Choix du style d'affichage

Button BACK : Retour
Button CANCEL : Fermer

**Pull request merged**
